# Generated by Django 3.2.13 on 2023-01-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
